//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TeknikServis
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBLARIZAFATURADETAY
    {
        public int DETAYID { get; set; }
        public Nullable<int> FATURAID { get; set; }
        public string URUNSERINO { get; set; }
        public string ALINANPARCA { get; set; }
        public Nullable<decimal> ALINANPARCAFIYATI { get; set; }
        public Nullable<decimal> SERVISUCRETI { get; set; }
        public string SORUN { get; set; }
        public string ACIKLAMA { get; set; }
        public string ISLEMLER { get; set; }
    
        public virtual TBLARIZAFATURA1 TBLARIZAFATURA { get; set; }
        public virtual TBLARIZAFATURA1 TBLARIZAFATURA1 { get; set; }
    }
}
