//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TeknikServis
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBLARIZAFATURA1
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TBLARIZAFATURA1()
        {
            this.TBLARIZAFATURADETAY = new HashSet<TBLARIZAFATURADETAY>();
        }
    
        public int ARIZAID { get; set; }
        public Nullable<int> ISLEMID { get; set; }
        public Nullable<decimal> ONFIYAT { get; set; }
        public Nullable<decimal> NETFIYAT { get; set; }
        public Nullable<System.DateTime> TARIH { get; set; }
        public Nullable<int> CARI { get; set; }
        public Nullable<short> PERSONEL { get; set; }
        public Nullable<int> FATURATIPID { get; set; }
    
        public virtual TBLURUNKABUL TBLURUNKABUL { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBLARIZAFATURADETAY> TBLARIZAFATURADETAY { get; set; }
        public virtual TBLFATURATIPLERI TBLFATURATIPLERI { get; set; }
        public virtual TBLCARI TBLCARI { get; set; }
        public virtual TBLPERSONEL TBLPERSONEL { get; set; }
    }
}
