//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TeknikServis
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBLFATURATIPLERI
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TBLFATURATIPLERI()
        {
            this.TBLARIZAFATURA = new HashSet<TBLARIZAFATURA1>();
            this.TBLFATURABILGI = new HashSet<TBLFATURABILGI>();
            this.TBLMALALIMFATURASI = new HashSet<TBLMALALIMFATURASI>();
            this.TBLMALSATIMFATURASI = new HashSet<TBLMALSATIMFATURASI>();
            this.TBLSATINALMAFATURASIBILGI = new HashSet<TBLSATINALMAFATURASIBILGI>();
            this.TBLSABITKIYMET = new HashSet<TBLSABITKIYMET>();
            this.TBLIADEFATURASI = new HashSet<TBLIADEFATURASI>();
        }
    
        public int ID { get; set; }
        public string FATURATIPI { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBLARIZAFATURA1> TBLARIZAFATURA { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBLFATURABILGI> TBLFATURABILGI { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBLMALALIMFATURASI> TBLMALALIMFATURASI { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBLMALSATIMFATURASI> TBLMALSATIMFATURASI { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBLSATINALMAFATURASIBILGI> TBLSATINALMAFATURASIBILGI { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBLSABITKIYMET> TBLSABITKIYMET { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBLIADEFATURASI> TBLIADEFATURASI { get; set; }
    }
}
