//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TeknikServis
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBLILCE
    {
        public int ID { get; set; }
        public string ILCE { get; set; }
        public Nullable<int> SEHIR { get; set; }
    
        public virtual TBLIL TBLIL { get; set; }
    }
}
