//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TeknikServis
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBLIRSALIYE
    {
        public int ID { get; set; }
        public Nullable<System.DateTime> TARIH { get; set; }
        public string SAAT { get; set; }
        public Nullable<int> CARI { get; set; }
        public Nullable<int> URUN { get; set; }
        public string URUNSERINO { get; set; }
        public string MARKA { get; set; }
        public string VERGIDAIRESI { get; set; }
        public Nullable<short> ADET { get; set; }
        public Nullable<decimal> FIYAT { get; set; }
        public Nullable<decimal> TUTAR { get; set; }
        public Nullable<System.DateTime> SEVKTARIHI { get; set; }
        public string SEVKSAATI { get; set; }
    
        public virtual TBLCARI TBLCARI { get; set; }
        public virtual TBLURUN TBLURUN { get; set; }
    }
}
