//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TeknikServis
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBLKULLANICI
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TBLKULLANICI()
        {
            this.TBLYETKITANIM = new HashSet<TBLYETKITANIM>();
        }
    
        public int ID { get; set; }
        public string KULLANICI_ADI { get; set; }
        public string KULLANICI_SOYADI { get; set; }
        public string KULLANICI { get; set; }
        public string SIFRE { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBLYETKITANIM> TBLYETKITANIM { get; set; }
    }
}
