//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TeknikServis
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBLSABITKIYMET
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TBLSABITKIYMET()
        {
            this.TBLMALALIMFATURASI = new HashSet<TBLMALALIMFATURASI>();
            this.TBLMALSATIMFATURASI = new HashSet<TBLMALSATIMFATURASI>();
        }
    
        public int ID { get; set; }
        public Nullable<short> PERSONEL { get; set; }
        public Nullable<short> ADET { get; set; }
        public string AD { get; set; }
        public Nullable<System.DateTime> TARIH { get; set; }
        public Nullable<int> FATURATIPIID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBLMALALIMFATURASI> TBLMALALIMFATURASI { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBLMALSATIMFATURASI> TBLMALSATIMFATURASI { get; set; }
        public virtual TBLPERSONEL TBLPERSONEL { get; set; }
        public virtual TBLFATURATIPLERI TBLFATURATIPLERI { get; set; }
    }
}
