//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TeknikServis
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBLYETKITANIM
    {
        public int ID { get; set; }
        public Nullable<int> YETKINUMARASI { get; set; }
        public string YETKIDURUMU { get; set; }
        public Nullable<int> KULLANICIID { get; set; }
    
        public virtual TBLKULLANICI TBLKULLANICI { get; set; }
        public virtual TBLYETKIDURUMU TBLYETKIDURUMU { get; set; }
    }
}
